### ISSUE TITLE
General 10.1 Citus release checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#1007]
- [x] Bump version
  - `:vimgrep '\(\<10\.\?0\>\)\|\(100_\)' **/*.rst *.py`
- [x] Update all installation steps to use new package name
- [x] Update our upgrade steps
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Debian 9 Stretch — ami-066a93633945763a8
    - [x] Debian 10 Buster — ami-0ea08f325bd2bbf69
    - [x] Ubuntu 16.04 Xenial — ami-0765f2a0e038358f8
    - [x] Ubuntu 18.04 Bionic Beaver — ami-0ee5e851705bfaf7a
    - [x] Ubuntu 20.04 Focal — ami-0cfc8da67f8bd8679
    - [x] CentOS 7 — ami-01e36b7901e884a10
    - [x] CentOS 8 — ami-000e7ce4dd68e7a11
    - [x] RHEL 7 — ami-015d91fd7a96cbfbd
    - [x] RHEL 8 — ami-00c1b07c4c4322ad4
- [x] Update citusdata.com/download links.
  - [x] Confirm with Claire that it goes live after merge
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] scan for any other udf and guc changes (in Community and Enterprise)
    - `git diff release-10.0 -- src/backend/distributed/shared_library_init.c`
    - `git diff release-10.0 -- src/backend/distributed/sql/udfs/`
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Test that the search box works
- [x] Create new 10.1 release branch and set as default ver in RTD (advanced settings tab)
- [x] Rebuild previous version so that canonical link gets updated
- [ ] Re-check old versions (does the version picker work, does search work)
- [ ] (later) Test enterprise install on one debian and one centos version
