### ISSUE TITLE
Citus 10.2 release checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#1013]
- [x] Bump version
  - `:vimgrep '\(\<10\.\?1\>\)\|\(101_\)' **/*.rst *.py`
- [x] Update all installation steps to use new package name
- [x] Update our upgrade steps
- [ ] Verify Installation steps with new packages (single-machine cluster install)
    - `docker run --rm -it --entrypoint bash image_name`
    - [x] Debian 9 Stretch
    - [x] Debian 10 Buster
    - [x] Ubuntu 18.04 Bionic Beaver
    - [x] Ubuntu 20.04 Focal
    - [x] CentOS 7
    - [x] CentOS 8
    - [x] RHEL 7 — ami-015d91fd7a96cbfbd
    - [x] RHEL 8 — ami-00c1b07c4c4322ad4
- [x] Update citusdata.com/download links.
  - [ ] Confirm with Claire that it goes live after merge
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
  -  Check for package https://hub.docker.com/r/citusdata/citus/tags?name=10.2
- [x] scan for any other udf and guc changes (in Community and Enterprise)
    - `git diff origin/release-10.1 origin/release-10.2 -- src/backend/distributed/shared_library_init.c`
    - `git diff origin/release-10.1 origin/release-10.2 -- src/backend/distributed/sql/udfs/`
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Create new 10.2 release branch
- [x] Test that the search box works in the new release branch
- [x] Set as default ver in RTD (advanced settings tab)
- [x] Rebuild previous version so that canonical link gets updated
- [x] Re-check old versions (does the version picker work, does search work)
- [ ] (later) Test enterprise install on one debian and one centos version
