### ISSUE TITLE
Citus 11.0-beta release checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#1037]
- [ ] Bump version
  - `:vimgrep '\(\<10\.\?2\>\)\|\(102_\)' **/*.rst *.py`
- [ ] Update all installation steps to use new package name
- [ ] Update our upgrade steps
- [ ] Verify Installation steps with new packages (single-machine cluster install)
    - `docker run --rm -it --entrypoint bash image_name`
    - [x] Debian 9 Stretch
    - [x] Debian 10 Buster
    - [x] Debian 11 Bullseye
    - [x] Ubuntu 18.04 Bionic Beaver
    - [x] Ubuntu 20.04 Focal
    - [x] CentOS 7 — `centos:7`
    - [ ] CentOS 8
      - PGDG repositories don't have postgresql14-server package for your operating system
    - [ ] RHEL 7 — ami-015d91fd7a96cbfbd
    - [ ] RHEL 8 — ami-00c1b07c4c4322ad4
- [ ] Update citusdata.com/download links.
  - [ ] Confirm with Claire that it goes live after merge
- [ ] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
  -  Check for package https://hub.docker.com/r/citusdata/citus/tags?name=10.2
- [ ] scan for any other udf and guc changes (in Community and Enterprise)
    - `git diff origin/release-10.1 origin/release-10.2 -- src/backend/distributed/shared_library_init.c`
    - `git diff origin/release-10.1 origin/release-10.2 -- src/backend/distributed/sql/udfs/`
- [ ] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [ ] Create new 11.0-beta release branch
- [ ] Test that the search box works in the new release branch
- [ ] Set as default ver in RTD (advanced settings tab)
- [ ] Rebuild previous version so that canonical link gets updated
- [ ] Re-check old versions (does the version picker work, does search work)
