### ISSUE TITLE
PG 15 checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#1066]
- [ ] Update all installation steps to use new package name
- [ ] Update our upgrade steps
- [ ] Verify Installation steps with new packages (single-machine cluster install)
    - `docker run --rm -it --entrypoint bash image_name`
    - [ ] Debian 9 Stretch
    - [ ] Debian 10 Buster
    - [ ] Debian 11 Bullseye
    - [ ] Ubuntu 18.04 Bionic Beaver
    - [ ] Ubuntu 20.04 Focal
    - [ ] CentOS 7 — `centos:7`
    - [ ] RHEL 7 — (Azure)
    - [ ] RHEL 8 — (Azure)
- [ ] Verify pg in docker image
- [ ] Update citusdata.com/download links.
  - [ ] Confirm with Claire that it goes live after merge
