### ISSUE TITLE
Citus 11.3 package testing checklist

### ISSUE THREAD

**Issue by pinodeca** [citusdata/citus_docs#1079]
- [x] Test installation steps to use new package name - note all changes required in the docs.
- [x] Test and take note of any/all changes required in upgrade steps
  - [x] Check that upgrade docs use valid ranges of PG and Citus versions  
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - `docker run --rm -it --entrypoint bash image_name`
    - [x] Debian 10 Buster
    - [x] Debian 11 Bullseye
    - [x] Ubuntu 18.04 Bionic Beaver
    - [x] Ubuntu 20.04 Focal
    - [x] Ubuntu 22
    - [x] CentOS 7 — `centos:7`
    - [x] RHEL 7 — (Azure)
    - [x] RHEL 8 — (Azure)
      - Installing pgdg repo... PGDG repositories don't have postgresql15-server package for your operating system
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
  -  Check for package https://hub.docker.com/r/citusdata/citus/tags?name=11.3

**Comment by aykut-bozkurt** [comment]
[Citus readme](https://github.com/citusdata/citus/blob/main/README.md#:~:text=sudo%20apt%2Dget%20%2Dy%20install%20postgresql%2D15%2Dcitus%2D11.2) points to old packages in a few places.

**Comment by pinodeca** [comment]
@aykut-bozkurt please sync with @jonels-msft on install/upgrade changes required in the docs.

**Comment by pinodeca** [comment]
Adam said he would submit a PR for the Citus readme.

**Comment by jonels-msft** [comment]
@aykut-bozkurt are there any issues with the postgres versions we picked to go with the citus versions in our install or upgrade instructions? I know sometimes Citus drops support for EOL postgres.
