### ISSUE TITLE
Citus 11.3 documentation update checklist

### ISSUE THREAD

**Issue by pinodeca** [citusdata/citus_docs#1080]
- [x] Ensure git cherry-picks up to date on master branch
- [x] Bump version
  - `:vimgrep '\(\<11\.\?2\>\)\|\(112_\)' **/*.rst *.py`
- [x] Update installation (need input from #1079)
- [x] Update our upgrade steps (need input from #1079)
- [x] Update citusdata.com/download links.
- [ ] scan for any other udf and guc changes (in Community and Enterprise)
    - `git diff origin/release-11.2 origin/release-11.3 -- src/backend/distributed/shared_library_init.c`
    - `git diff origin/release-11.2 origin/release-11.3 -- src/backend/distributed/sql/udfs/`
    - Also check https://github.com/citusdata/citus/pull/6856
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Create new 11.3 release branch
- [x] Test that the search box works in the new release branch
- [x] Set as default ver in RTD (advanced settings tab)
- [x] Rebuild previous version so that canonical link gets updated
- [ ] Re-check old versions (does the version picker work, does search work)
