### ISSUE TITLE
Citus 12.0 documentation update checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#1101]
- [x] Ensure git cherry-picks up to date on master branch
- [x] Bump version
  - `:vimgrep '\(\<11\.\?3\>\)\|\(113_\)' **/*.rst *.py`
- [x] Update installation
- [x] Update our upgrade steps
- [x] Update citusdata.com/download links.
- [x] scan for any other udf and guc changes (in Community and Enterprise)
    - `git diff origin/release-11.3 origin/release-12.0 -- src/backend/distributed/shared_library_init.c`
    - `git diff origin/release-11.3 origin/release-12.0 -- src/backend/distributed/sql/udfs/`
    - Also check https://github.com/citusdata/citus/pull/7049
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Create new 12.0 release branch (`v12.0`)
- [x] Set as default ver in RTD (advanced settings tab)
- [x] Rebuild previous version so that canonical link gets updated
