### ISSUE TITLE
6.1 release general checklist

### ISSUE THREAD

**Issue by sumedhpathak** [citusdata/citus_docs#230]
- [x] Create new 6.1 release branch (last step)

- [x] Verify / Update major-version upgrade steps (Joe)

- [x] Verify / Update minor-version upgrade steps (Joe)

- [ ] Check / Document new UDF's added in 6.1

- [x] Check / Document new config options added in 6.1

- [x] Create and test new Tutorial bundles (Mac/Linux) for 6.1 ([steps](https://github.com/citusdata/citus-tutorial)) (Joe)

- [x] Update links from Readme and Citus web site to newer version of docs if required

- [x] Update links to new Tutorial bundles (Joe)

- [x] Update links to new CloudFormation template (Sumedh)

- [x] Verify Installation steps with new packages

- [x] Update all installation steps to use new package name (CloudFormation, Website instructions) (Sumedh)
