### ISSUE TITLE
7.0 Release General Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#435]
- [x] s/6\\.\d/7.0/g
- [x] Verify / Update major-version upgrade steps
    - Check that it says 6->7 rather than 5->6
- [x] Check / Document new UDF's added in 7
- [x] Check / Document new config options added in 7
- [x] Update links from Readme and Citus web site to newer version of docs if required
   - (remove this item if they all point at stable now)
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Update links to new CloudFormation template (Burak)
- [x] Verify Installation steps with new packages
    - [x] Ubuntu 16.04 (Joe)
    - [x] Ubuntu 14.04
    - [x] Debian Jessie
    - [x] Debian Wheezy
    - [x] Amazon Linux 2017.03.0
    - [x] CentOS 7.3
    - [x] CentOS 6.9
    - [x] RHEL 7.2 
    - [x] RHEL 6.5 
    - [x] Fedora 26
    - [x] Fedora 25
- [x] Test Multi-tenant tutorial and use-case guide (on just one version) (Sumedh)
- [x] Test Real-time analytics tutorial and use-case guide (on just one version) (Joe)
- [x] Test Docker installation. 
- [x] Update citusdata.com/download links.
- [x] Create new 7.0 release branch and set as default ver in RTD (last step)

**Comment by begriffs** [comment]
Verified that Citus installs on the Debian family (it identifies as 7.0-15). Also checked Ubuntu 16.04 *32-bit* and that failed, but I suspect that we're intentionally not providing 32-bit Citus packages.

**Comment by sumedhpathak** [comment]
I've verified RHEL, but no package was found for Fedora 25. I opened an issue in the packaging repo. https://github.com/citusdata/packaging/issues/71. 

Continuing on to tutorial and use-case guide.

**Comment by sumedhpathak** [comment]
Testing Docker, and https://raw.githubusercontent.com/citusdata/docker/master/docker-compose.yml still pull 6.2.3. @jasonmp85 Where do we update this file?

**Comment by begriffs** [comment]
Noting that the real-time use case guide does not work for me. The script to load fake http requests keeps inserting them but the ingest_time is always the exact same. When I kill the loop and start it again it starts with a new time and keeps repeating that new one.

For instance, try running the ingestion loop a few times, then check:

```
select count(*), ingest_time from http_request where site_id = 1 group by ingest_time;
```
There will be only as many entries as the number of times you run the loop.
