### ISSUE TITLE
General 7.1 Release Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#528]
- [x] s/7\\.0/7.1/g
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Update links to new CloudFormation template
- [x] Verify Installation steps with new packages
    - [x] Ubuntu 16.04 (Joe)
    - [x] Ubuntu 14.04
    - [x] Debian Jessie
    - [x] Debian Wheezy
    - [x] Amazon Linux 2017.03.0
    - [x] CentOS 7.3
    - [x] CentOS 6.9
    - [x] RHEL 7.2 
    - [x] RHEL 6.5 
    - [x] Fedora 26
    - [ ] Fedora 25
- [x] Test 7.0 -> 7.1 upgrade instructions
- [x] Test 7.1, pg 9.6 -> pg 10 upgrade instructions
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on just one version)
- [x] Test Docker installation. 
- [x] Update citusdata.com/download links.
- [x] Create new 7.1 release branch and set as default ver in RTD (last step)

**Comment by begriffs** [comment]
Done.
