### ISSUE TITLE
General 7.2 Release Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#591]
(Note when copying this list for the next version, remove Amazon Linux and Fedora from the test list.)

- [x] s/7\\.1/7.2/g
- [x] Update all installation steps to use new package name (except CloudFormation)
- [ ] Update links to new CloudFormation template
    - Holding off on this while the bugs are worked out of the template for 7.2
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Ubuntu 16.04 (Joe)
    - [x] Ubuntu 14.04
    - [x] Debian Jessie
    - [x] Debian Wheezy
    - [ ] Amazon Linux 2017.03.0
      ```
      # using amzn-ami-hvm-2017.03.0.20170401-x86_64-ebs (ami-0efeda6b)
      Detected operating system as amzn/2017.
      Unfortunately, your operating system distribution and version are not supported by this script.
      ```
    - [x] CentOS 7.3
    - [x] CentOS 6.9
    - [x] RHEL 7.2
    - [x] RHEL 6.5  (couldn't find 6.5, using 6.8)
    - [x] Fedora 26
    - [ ] Fedora 25 (Hard to find, used Fedora 27)
      ```
      sudo yum install -y citus72_10
      Last metadata expiration check: 0:00:27 ago on Wed 17 Jan 2018 07:37:54 PM UTC.
      No match for argument: citus72_10
      Error: Unable to find a match
      ```
- [x] Update our upgrade steps
  - [x] Ubuntu 16.04: installed 7.0, upgraded to 7.2 with minor ver steps 
  - [x] RHEL 7.4: 7.1 -> 7.2 (with pg 10)
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on just one version)
- [x] Test Docker installation.
- [x] Verify there are no Sphinx warnings in local build
- [x] Update citusdata.com/download links.
- [x] Create new 7.2 release branch and set as default ver in RTD (last step)

**Comment by begriffs** [comment]
Installing community packages for pg 10 worked fine but for 9.6 it's failing. On RHEL 7.4:

```
$ sudo yum install -y citus72_96
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package citus72_96.x86_64 0:7.2.0.citus-1.el7.centos will be installed
--> Processing Dependency: postgresql96-server for package: citus72_96-7.2.0.citus-1.el7.centos.x86_64
--> Processing Dependency: libpq.so.5()(64bit) for package: citus72_96-7.2.0.citus-1.el7.centos.x86_64
--> Running transaction check
---> Package citus72_96.x86_64 0:7.2.0.citus-1.el7.centos will be installed
--> Processing Dependency: postgresql96-server for package: citus72_96-7.2.0.citus-1.el7.centos.x86_64
---> Package postgresql-libs.x86_64 0:9.2.23-3.el7_4 will be installed
--> Finished Dependency Resolution
Error: Package: citus72_96-7.2.0.citus-1.el7.centos.x86_64 (citusdata_community)
           Requires: postgresql96-server
```

**Comment by sumedhpathak** [comment]
Chatted with Joe offline, and this isn't a problem. The packages exist, but we currently install the PG10 specific PGDG repo. https://www.postgresql.org/download/linux/redhat/. For RHEL Postgres has a different repo for each PG version. Users can manually install the 9.6 version to get the 9.6 specific 7.2 packages.

**Comment by sumedhpathak** [comment]
@begriffs You also intend to open up a PR for review once done testing?
