### ISSUE TITLE
General 7.3 Release Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#622]
- [x] s/7\\.2/7.3/g
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Update links to new CloudFormation template
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Ubuntu 16.04 (Joe)
    - [x] Ubuntu 14.04
    - [x] Debian Jessie
    - [x] Debian Wheezy
    - [x] CentOS 7.3  (used 7.4 actually)
    - [x] CentOS 6.9
    - [x] RHEL 7.2  (7.4 actually)
    - [x] RHEL 6.8  (6.9 actually)
- [x] Update our upgrade steps
    - [x] Test upgrade steps  (7.2->7.3 minor upgrade on pg 10, ubuntu)
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on just one version)
    - The use-case guide failed on docker for the HLL part, though:
      ```sql
      create extension hll;
      -- ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/hll.control": No such file or directory
      ```
- [x] Test Docker installation.
- [x] Verify there are no Sphinx warnings in local build
- [x] Update citusdata.com/download links.
- [ ] Create new 7.3 release branch and set as default ver in RTD
- [ ] Verify that RTD adds functioning analytics code
