### ISSUE TITLE
General 7.4 Release Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#671]
- [x] s/7\\.3/7.4/g
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Update links to new CloudFormation template
  - [x] Test deploying CF template as non-Citus user to verify public permissions
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Ubuntu 16.04 (Joe)
    - [x] Ubuntu 14.04
    - [x] Debian Jessie
    - [x] Debian Wheezy
    - [x] CentOS 7.4
    - [x] CentOS 6.9
    - [x] RHEL 7.5
    - [x] RHEL 6.9
- [x] Update our upgrade steps
    - [x] Test upgrade steps  (7.3->7.4 minor upgrade on pg 10, ubuntu)
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on just one version)
    - The use-case guide failed on docker for the HLL part, though:
      ```sql
      create extension hll;
      -- ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/hll.control": No such file or directory
      ```
- [x] Test Docker installation.
- [x] Verify there are no Sphinx warnings in local build
- [x] Update citusdata.com/download links.
- [x] Create new 7.4 release branch and set as default ver in RTD
- [x] Verify that RTD adds functioning analytics code
- [x] Verify heap and segment
- [x] Rebuild previous version so that canonical link gets updated
