### ISSUE TITLE
General 7.5 Release Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#730]
- [x] s/7\\.4/7.5/g
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Update links to new CloudFormation template
  - [x] Test deploying CF template (citus_version() is Citus 7.5.0 on x86_64-pc-linux-gnu)
  - [x] curl the template as anonymous user to verify public permissions
- [ ] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Ubuntu 16.04 (Joe)
    - [x] Ubuntu 14.04
    - [x] Debian Jessie
    - [x] Debian Wheezy
    - [x] CentOS 7.4
    - [x] CentOS 6.9
    - [x] RHEL 7.5
    - [x] RHEL 6.9
- [x] Update our upgrade steps
    - [x] Test upgrade steps  (7.4->7.5 minor upgrade on pg 10, ubuntu)
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] Verify there are no Sphinx warnings in local build
- [x] Update citusdata.com/download links. (https://github.com/citusdata/citusdata.com/pull/237)
- [x] Create new 7.5 release branch and set as default ver in RTD
- [x] Verify that RTD adds functioning analytics code
- [x] Verify heap and segment
- [x] Rebuild previous version so that canonical link gets updated
- [x] Duplicate RTD page redirects from previous to new version
