### ISSUE TITLE
General 8.0 Release Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#798]
- [x] s/7\\.5/8.0/g
  - `find . -name '*.rst' -exec grep -Hn '\(\b7\.\?[1-5]\b\)\|\(7[1-5]_\)' {} \;`
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Update links to new CloudFormation template
  - [x] Test deploying CF template (check citus_version)
    - All good except it does use postgres 9.6.10 which is slightly old
  - [x] curl the urldecoded templateURL as anonymous user to verify public permissions
- [x] Update docs to use pg 11 rather than 10
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Ubuntu 18.04
    - [x] Ubuntu 16.04 (Joe)
    - [x] Debian Stretch
    - [x] Debian Jessie
    - [x] CentOS 7.5
    - [x] CentOS 6.9
    - [x] RHEL 7.5
    - [x] RHEL 6.9
- [x] Update our upgrade steps
    - [x] Test 7.5->8.0 major upgrade on pg 10, ubuntu
    - [x] Test 8.0/10 -> 8.0/11
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] Verify there are no Sphinx warnings in local build
    - (Remove _build directory and try fresh too)
- [x] Update citusdata.com/download links. (https://github.com/citusdata/citusdata.com/pull/256)
  - [x] Confirm with Claire that it goes live after merge
- [x] Create new 8.0 release branch and set as default ver in RTD
- [x] Verify that RTD adds functioning analytics code
- [ ] Verify heap and segment
- [x] Rebuild previous version so that canonical link gets updated
- [x] Duplicate RTD page redirects from previous to new version
- [x] Add redirect for MX leaving the cloud section

**Comment by begriffs** [comment]
Ran into a problem where https://install.citusdata.com/community/rpm.sh installs pgdg10 so citus80_11 can't be installed. The script is probably not yet updated.

**Comment by begriffs** [comment]
Running into an error in the db upgrade. On a fresh ubuntu 18.04 ec2 instance, I ran this:

```sh
curl https://install.citusdata.com/community/deb.sh | sudo bash

sudo apt-get -y install postgresql-10-citus-7.5

sudo su - postgres

export PATH=$PATH:/usr/lib/postgresql/10/bin

cd ~
mkdir -p citus/coordinator citus/worker1
initdb -D citus/coordinator
initdb -D citus/worker1

echo "shared_preload_libraries = 'citus'" >> citus/coordinator/postgresql.conf
echo "shared_preload_libraries = 'citus'" >> citus/worker1/postgresql.conf


pg_ctl -D citus/coordinator -o "-p 9700" -l coordinator_logfile start
pg_ctl -D citus/worker1 -o "-p 9701" -l worker1_logfile start


psql -p 9700 -c "CREATE EXTENSION citus;"
psql -p 9701 -c "CREATE EXTENSION citus;"

psql -p 9700 -c "SELECT * from master_add_node('localhost', 9701);"


#### load/distribute MT data

psql -p 9700

CREATE TABLE        public.pg_dist_partition AS
  SELECT * FROM pg_catalog.pg_dist_partition;
CREATE TABLE        public.pg_dist_shard AS
  SELECT * FROM pg_catalog.pg_dist_shard;
CREATE TABLE        public.pg_dist_placement AS
  SELECT * FROM pg_catalog.pg_dist_placement;
CREATE TABLE        public.pg_dist_node_metadata AS
  SELECT * FROM pg_catalog.pg_dist_node_metadata;
CREATE TABLE        public.pg_dist_node AS
  SELECT * FROM pg_catalog.pg_dist_node;
CREATE TABLE        public.pg_dist_local_group AS
  SELECT * FROM pg_catalog.pg_dist_local_group;
CREATE TABLE        public.pg_dist_transaction AS
  SELECT * FROM pg_catalog.pg_dist_transaction;
CREATE TABLE        public.pg_dist_colocation AS
  SELECT * FROM pg_catalog.pg_dist_colocation;


#### exit back to ubuntu user

sudo apt-get -y install postgresql-11-citus-8.0

sudo su - postgres

export PATH=$PATH:/usr/lib/postgresql/11/bin

cd ~
mkdir -p citus/8-coordinator citus/8-worker1
initdb -D citus/8-coordinator
initdb -D citus/8-worker1

echo "shared_preload_libraries = 'citus'" >> citus/8-coordinator/postgresql.conf
echo "shared_preload_libraries = 'citus'" >> citus/8-worker1/postgresql.conf

export OLD_PG_DATA=citus/coordinator
export OLD_PG_PATH=/usr/lib/postgresql/10
export NEW_PG_DATA=citus/8-coordinator
export NEW_PG_PATH=/usr/lib/postgresql/11

$OLD_PG_PATH/bin/pg_ctl -D citus/coordinator stop
$OLD_PG_PATH/bin/pg_ctl -D citus/worker1 stop

$NEW_PG_PATH/bin/pg_upgrade -b $OLD_PG_PATH/bin/ -B $NEW_PG_PATH/bin/ \
                            -d $OLD_PG_DATA -D $NEW_PG_DATA

export OLD_PG_DATA=citus/worker1
export NEW_PG_DATA=citus/8-worker1

$NEW_PG_PATH/bin/pg_upgrade -b $OLD_PG_PATH/bin/ -B $NEW_PG_PATH/bin/ \
                            -d $OLD_PG_DATA -D $NEW_PG_DATA

pg_ctl -D citus/8-coordinator -o "-p 9700" -l coordinator_logfile start
pg_ctl -D citus/8-worker1 -o "-p 9701" -l worker1_logfile start
```

Now I attempt to restore the metadata on the new coordinator. `psql -p 9700`:
```
postgres=# INSERT INTO pg_catalog.pg_dist_partition
postgres-#   SELECT * FROM public.pg_dist_partition;
ERROR:  loaded Citus library version differs from installed extension version
DETAIL:  Loaded library requires 8.0, but the installed extension version is 7.5-7.
HINT:  Run ALTER EXTENSION citus UPDATE and try again.
postgres=# INSERT INTO pg_catalog.pg_dist_shard
postgres-#   SELECT * FROM public.pg_dist_shard;
ERROR:  loaded Citus library version differs from installed extension version
DETAIL:  Loaded library requires 8.0, but the installed extension version is 7.5-7.
HINT:  Run ALTER EXTENSION citus UPDATE and try again.
postgres=# INSERT INTO pg_catalog.pg_dist_placement
postgres-#   SELECT * FROM public.pg_dist_placement;
ERROR:  loaded Citus library version differs from installed extension version
DETAIL:  Loaded library requires 8.0, but the installed extension version is 7.5-7.
HINT:  Run ALTER EXTENSION citus UPDATE and try again.
postgres=# INSERT INTO pg_catalog.pg_dist_node_metadata
postgres-#   SELECT * FROM public.pg_dist_node_metadata;
INSERT 0 1
postgres=# INSERT INTO pg_catalog.pg_dist_node
postgres-#   SELECT * FROM public.pg_dist_node;
ERROR:  loaded Citus library version differs from installed extension version
DETAIL:  Loaded library requires 8.0, but the installed extension version is 7.5-7.
HINT:  Run ALTER EXTENSION citus UPDATE and try again.
postgres=# TRUNCATE TABLE pg_catalog.pg_dist_local_group;
ERROR:  could not find any entries in pg_dist_local_group
postgres=# INSERT INTO pg_catalog.pg_dist_local_group
postgres-#   SELECT * FROM public.pg_dist_local_group;
INSERT 0 1
postgres=# INSERT INTO pg_catalog.pg_dist_transaction
postgres-#   SELECT * FROM public.pg_dist_transaction;
INSERT 0 0
postgres=# INSERT INTO pg_catalog.pg_dist_colocation
postgres-#   SELECT * FROM public.pg_dist_colocation;
INSERT 0 1
```

**Comment by begriffs** [comment]
I think what I have to do is upgrade 7.5/10 -> 7.5/11 -> 8.0/11. Can't update both the db and citus versions at once.

**Comment by begriffs** [comment]
Github closed this because it was linked to the 8.0 PR, but there are still some more items to do, so reopening.
