### ISSUE TITLE
General 8.1 Release Checklist

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#825]
- [x] s/8\\.0/8.1/g
  - `find . -name '*.rst' -exec grep -Hn '\(\b8\.\?0\b\)\|\(80_\)' {} \;`
- [x] Update all installation steps to use new package name (except CloudFormation)
- [ ] Update links to new CloudFormation template
  - Actually not doing that for this release quite yet
  - [ ] Test deploying CF template (check citus_version)
  - [ ] curl the urldecoded templateURL as anonymous user to verify public permissions
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Ubuntu 18.04
    - [x] Ubuntu 16.04 (Joe)
    - [x] Debian Stretch
    - [x] Debian Jessie
    - [x] CentOS 7.5
    - [x] CentOS 6.9
    - [x] RHEL 7.6
    - [x] RHEL 6.9
- [x] Update our upgrade steps
    - [x] Test 8.0->8.1 minor upgrade on pg 11, ubuntu
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] Verify there are no Sphinx warnings in local build
    - (Remove _build directory and try fresh too)
- [x] Update citusdata.com/download links. (https://github.com/citusdata/citusdata.com/pull/256)
  - [x] Confirm with Claire that it goes live after merge
- [x] Create new 8.1 release branch and set as default ver in RTD
- [x] Verify that RTD adds functioning analytics code
- [x] Verify window.heap
- [x] Clear cookies and verify that cookie consent confirmation appears in new version
- [x] Rebuild previous version so that canonical link gets updated
- [x] Duplicate RTD page redirects from previous to new version
