### ISSUE TITLE
General 9.0 release checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#882]
- [x] s/8\\.3/9.0/g
  - `:vimgrep '\(\<8\.\?3\>\)\|\(83_\)' **/*.rst`
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Ubuntu 18.04 Bionic Beaver
    - [x] Ubuntu 16.04 Xenial
    - [x] Debian 9 Stretch
    - [ ] CentOS 6
      - Cannot find citus90_12 package
    - [x] CentOS 7
    - [x] RHEL 7
    - [ ] RHEL 8
      - Cannot find citus90_12 package
- [x] Update our upgrade steps
	- [x] Test (pg 11 -> 12RC) upgrade process with UDFs, rewrite that section of docs
	- [x] Test pg 11 (citus 8.3 -> 9) upgrade process
            - [x] apt system
            - [x] rpm system
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] Update extra/enterprise.html to not use rebalancer package
- [x] update master_add_node signature in reference docs
- [x] add/update claims about propagation of "create type”
- [x] scan for any other udf and guc changes
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [ ] Update citusdata.com/download links.
  - [ ] Confirm with Claire that it goes live after merge
- [ ] Create new 9.0 release branch and set as default ver in RTD
- [ ] Verify that RTD adds functioning analytics code
- [ ] Verify window.heap
- [ ] Clear cookies and verify that cookie consent confirmation appears in new version
- [ ] Rebuild previous version so that canonical link gets updated
- [ ] Duplicate RTD page redirects from previous to new version
