### ISSUE TITLE
General 9.1 Release Checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#890]
- [x] s/9\\.0/9.1/g
  - `:vimgrep '\(\<9\.\?0\>\)\|\(90_\)' **/*.rst`
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Debian 8 Jessie
    - [x] Debian 9 Stretch
    - [ ] Debian 10 Buster
       - Can't find an AMI that doesn't require subscription
    - [x] Ubuntu 18.04 Bionic Beaver
    - [x] Ubuntu 16.04 Xenial
    - [x] CentOS 6
    - [x] CentOS 7
    - [ ] CentOS 8
       - Can't find an AMI that doesn't require subscription
    - [x] RHEL 6
    - [x] RHEL 7
    - [x] RHEL 8
- [x] Update our upgrade steps
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
    - Tested Citus 9.1.0 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609, 64-bit
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] scan for any other udf and guc changes
    - Too extensive to incorporate into this PR
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Update citusdata.com/download links.
  - [x] Confirm with Claire that it goes live after merge
- [x] Create new 9.1 release branch and set as default ver in RTD
- [x] Rebuild previous version so that canonical link gets updated
- [ ] Duplicate RTD page redirects from previous to new version
