### ISSUE TITLE
General 9.2 Release Checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#903]
- [x] s/9\\.1/9.2/g
  - `:vimgrep '\(\<9\.\?1\>\)\|\(91_\)' **/*.rst`
- [x] Update all installation steps to use new package name (except CloudFormation)
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Debian 8 Jessie
    - [x] Debian 9 Stretch
    - [x] Debian 10 Buster
       - (use azure)
    - [x] Ubuntu 18.04 Bionic Beaver
    - [x] Ubuntu 16.04 Xenial
    - [x] CentOS 6
    - [x] CentOS 7
    - [x] CentOS 8
       - (Search for AMI...)
    - [x] RHEL 6
    - [x] RHEL 7
    - [x] RHEL 8
- [x] Update our upgrade steps
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] scan for any other udf and guc changes
    - GUC/UDF Changes are accounted for in other open issues
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Update citusdata.com/download links.
  - [ ] Confirm with Claire that it goes live after merge
- [x] Create new 9.2 release branch and set as default ver in RTD
- [x] Rebuild previous version so that canonical link gets updated
- [ ] Duplicate RTD page redirects from previous to new version
