### ISSUE TITLE
General 9.3 Citus checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#927]
- [x] s/9\\.2/9.3/g
  - `:vimgrep '\(\<9\.\?2\>\)\|\(92_\)' **/*.rst *.py`
- [x] Update all installation steps to use new package name
- [x] Update our upgrade steps
- [ ] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Debian 8 Jessie
    - [x] Debian 9 Stretch
    - [x] Debian 10 Buster
    - [x] Ubuntu 18.04 Bionic Beaver
    - [x] Ubuntu 16.04 Xenial
    - [x] Ubuntu 20.04 Focal
    - [ ] CentOS 6
      - epoll_ctl error
    - [x] CentOS 7
    - [x] CentOS 8
    - [ ] RHEL 6
      - epoll_ctl error
    - [x] RHEL 7
    - [x] RHEL 8
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] scan for any other udf and guc changes (in Community and Enterprise)
    - `git diff release-9.2 -- src/backend/distributed/shared_library_init.c`
    - `git diff release-9.2 -- src/backend/distributed/sql/udfs/`
- [x] Scan for updated extensions on Citus Cloud
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Update citusdata.com/download links.
  - [ ] Confirm with Claire that it goes live after merge
- [x] Create new 9.3 release branch and set as default ver in RTD (advanced settings tab)
- [x] Rebuild previous version so that canonical link gets updated
- [ ] Duplicate RTD page redirects from previous to new version
