### ISSUE TITLE
General 9.4 Citus release checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#950]
- [x] Bump version
  - `:vimgrep '\(\<9\.\?3\>\)\|\(93_\)' **/*.rst *.py`
- [x] Update all installation steps to use new package name
- [x] Update our upgrade steps
- [x] Verify Installation steps with new packages (single-machine cluster install)
    - [x] Debian 8 Jessie — ami-0e79236b
      - barely works, packages require https://unix.stackexchange.com/a/508728
    - [x] Debian 9 Stretch — ami-066a93633945763a8
    - [x] Debian 10 Buster — ami-0ea08f325bd2bbf69
    - [x] Ubuntu 16.04 Xenial — ami-0765f2a0e038358f8
    - [x] Ubuntu 18.04 Bionic Beaver — ami-0ee5e851705bfaf7a
    - [x] Ubuntu 20.04 Focal — ami-0cfc8da67f8bd8679
    - [ ] CentOS 6 — ami-0db8e77c005d79e33
      - epoll_ctl error
    - [x] CentOS 7 — ami-01e36b7901e884a10
    - [x] CentOS 8 — ami-04703ea1a1d8f892f
    - [ ] RHEL 6 — ami-02d0e2f9af142f67e
      - epoll_ctl error
    - [x] RHEL 7 — ami-015d91fd7a96cbfbd
    - [x] RHEL 8 — ami-00c1b07c4c4322ad4
- [x] Test Multi-tenant tutorial and use-case guide (on just one version)
- [x] Test Real-time analytics tutorial and use-case guide (on Docker)
    - Note it's been a while since I've tested the docker/docker-compose install instruction section
- [x] scan for any other udf and guc changes (in Community and Enterprise)
    - `git diff release-9.3 -- src/backend/distributed/shared_library_init.c`
    - `git diff release-9.3 -- src/backend/distributed/sql/udfs/`
- [x] Scan for updated extensions on Citus Cloud
    - Note HLL was downgraded: 2.14 -> 2.13
- [x] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [x] Test enterprise install on one debian and one centos version
- [x] Update citusdata.com/download links.
  - [x] Confirm with Claire that it goes live after merge
- [x] Create new 9.4 release branch and set as default ver in RTD (advanced settings tab)
- [x] Rebuild previous version so that canonical link gets updated
- [ ] Duplicate RTD page redirects from previous to new version
