### ISSUE TITLE
General 9.5 release checklist

### ISSUE THREAD

**Issue by jonels-msft** [citusdata/citus_docs#961]
- [ ] Bump version
  - `:vimgrep '\(\<9\.\?4\>\)\|\(94_\)' **/*.rst *.py`
- [ ] Update all installation steps to use new package name
- [ ] Update our upgrade steps
- [ ] Verify Installation steps with new packages (single-machine cluster install)
    - [ ] Debian 8 Jessie — ami-0e79236b
      - note, may require https://unix.stackexchange.com/a/508728
    - [ ] Debian 9 Stretch — ami-066a93633945763a8
    - [ ] Debian 10 Buster — ami-0ea08f325bd2bbf69
    - [ ] Ubuntu 16.04 Xenial — ami-0765f2a0e038358f8
    - [ ] Ubuntu 18.04 Bionic Beaver — ami-0ee5e851705bfaf7a
    - [ ] Ubuntu 20.04 Focal — ami-0cfc8da67f8bd8679
    - [ ] CentOS 6 — ami-0db8e77c005d79e33
    - [ ] CentOS 7 — ami-01e36b7901e884a10
    - [ ] CentOS 8 — ami-04703ea1a1d8f892f
    - [ ] RHEL 6 — ami-02d0e2f9af142f67e
    - [ ] RHEL 7 — ami-015d91fd7a96cbfbd
    - [ ] RHEL 8 — ami-00c1b07c4c4322ad4
- [ ] Test Multi-tenant tutorial and use-case guide (on just one version)
- [ ] Test Real-time analytics tutorial and use-case guide (on Docker)
- [x] scan for any other udf and guc changes (in Community and Enterprise)
    - Did this already in a separate task for 9.5
- [ ] Scan for updated extensions on Citus Cloud
- [ ] Verify there are no Sphinx warnings in local build
    - `sphinx-build -b html -a -n -W . _build`
    - (Remove _build directory and try fresh too)
- [ ] Test enterprise install on one debian and one centos version
- [ ] Update citusdata.com/download links.
  - [ ] Confirm with Claire that it goes live after merge
- [ ] Create new 9.5 release branch and set as default ver in RTD (advanced settings tab)
- [ ] Rebuild previous version so that canonical link gets updated
